name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: docker login -u thirupathireddy22/fastapi-app -p dckr_pat_o5_QMFNvJqIvDonbM7mb4gG0-5k

    - name: Pull Docker image
      run: docker pull thirupathireddy22/fastapi-app/my-fastapi-app:latest

    - name: Run unit tests
      run: docker run --rm thirupathireddy22/fastapi-app/my-fastapi-app python -m unittest unit.py

    - name: Deploy Docker image
      run: |
        docker tag thirupathireddy22/fastapi-app/my-fastapi-app:latest thirupathireddy22/fastapi-app/my-fastapi-app:main
        docker push thirupathireddy22/fastapi-app/my-fastapi-app:main
