name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo $DOCKERHUB_TOKEN | docker login -u dckr_pat_o5_QMFNvJqIvDonbM7mb4gG0-5k-app --password-stdin

    - name: Pull Docker image
      run: docker pull thirupathireddy22/fastapi-app:latest

    - name: Run unit tests
      run: docker run --rm thirupathireddy22/fastapi-app python -m unittest unit.py

    - name: Deploy Docker image
      run: |
        docker tag thirupathireddy22/fastapi-app:latest thirupathireddy22/fastapi-app:main
        docker push thirupathireddy22/fastapi-app:main
