name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: docker login -u your-dockerhub-username -p your-dockerhub-token

    - name: Pull Docker image
      run: docker pull your-dockerhub-username/my-fastapi-app:latest

    - name: Run unit tests
      run: docker run --rm your-dockerhub-username/my-fastapi-app python -m unittest unit.py

    - name: Deploy Docker image
      run: |
        docker tag your-dockerhub-username/my-fastapi-app:latest your-dockerhub-username/my-fastapi-app:main
        docker push your-dockerhub-username/my-fastapi-app:main
