name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: docker login -u thirupathireddy22 -p your-dockerhub-token

    - name: Pull Docker image
      run: docker pull thirupathireddy22/my-fastapi-app:latest

    - name: Run unit tests
      run: docker run --rm thirupathireddy22/my-fastapi-app python -m unittest unit.py

    - name: Deploy Docker image
      run: |
        docker tag thirupathireddy22/my-fastapi-app:latest thirupathireddy22/my-fastapi-app:main
        docker push thirupathireddy22/my-fastapi-app:main
