name: CI/CD Pipeline

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: docker login -u thirupathireddy22 -p ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Pull Docker image
      run: docker pull my-fastapi-app:latest

    - name: Run unit tests
      run: docker run --rm my-fastapi-app:latest python -m unittest unit.py

    - name: Deploy Docker image
      run: |
        docker tag my-fastapi-app:latest thirupathireddy22/fastapi-app:main
        docker push thirupathireddy22/fastapi-app:main
