name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and test Docker image
      run: |
        docker build -t my-fastapi-app .
        docker run --rm my-fastapi-app python -m unittest unit.py

    - name: Tag and push Docker image
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        docker tag my-fastapi-app your-dockerhub-username/my-fastapi-app:latest
        echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
        docker push your-dockerhub-username/my-fastapi-app:latest
